### ISSUE TITLE
Error: SSL connect error

### ISSUE THREAD

**Issue by webodan** [Arkq/cmusfm#15]
Hello,

I can't get cmusfm to scrobble with last.fm. I tried initing it for the first time and authing it with the service, and it seems like it will work but when I play files it simply doesn't. 

When I retry cmusfm init again to fetch a new key, it gives out an "SSL connect error". After checking the configure log I noticed that I didn't have openssl/md5 (which was the only dependency left uninistalled) so, thinking this error related to a lack of this dev library, I installed it (was libssl-dev in my debian wheezy), and tried recompiling and reinstalling cmusfm, but it still gives me this error and I'm out of ideas. ALso when I init cmusfm it always fails to check my previous session it says "Checking previous session (user: username) ...failed."

 Could I please get some insight on what to fix this?

Thanks in advance.

**Comment by Arkq** [comment]
Unfortunately I'm not able to reproduce this SSL error...

> I didn't have openssl/md5 (which was the only dependency left uninistalled) so, thinking this error related to a lack of this dev library, I installed it (was libssl-dev in my debian wheezy), and tried recompiling and reinstalling cmusfm, but it still gives me this error and I'm out of ideas.

There was a lot of troubles with MD5 functionality on OS X, so right now it is not required. If MD5 functionality is available on a host, it is used, otherwise bundled MD5 library is "included".

One thing, that comes to my mind, is that your libcurl library lacks SSL support. However, is would be strange since you are using Debian. Or maybe it was some temporal, problem with last.fm - I've seen it before (strobling service was not available for a day or two).

Also you might try to compile cmusfm with debug enabled (`../configure --enable-libnotify`). With this flag enabled, cmusfm will print a lot of debug messages. Maybe some hint will be there.
