### ISSUE TITLE
Not all songs are being scrobbled

### ISSUE THREAD

**Issue by alo0oz** [Arkq/cmusfm#21]
I can reproduce the problem every 3 times out of 5 playing music.

**Comment by Arkq** [comment]
Please, check current master, because this issue might be related to #22 . If it is still not working, I would need some more info, e.g. if song name contains non-ASCII characters, whether you are scrobbling from local file or internet radio. The best way to check this issue would be to compile cmusfm with debug enabled: `../configure --enable-debug`, then kill every instance of running cmusfm (`pkill cmusfm`) and start cmusfm server in a separate shell: `cmusfm server`. After this setup start to scrobble, there should be a lot of debug information, maybe something will be there.

Note:
Do not post these raw logs here, because there will be your Last.fm API key exposed. Before posting remove every occurrence of `user` and `key`, which can be found in the `.config/cmus/cmusfm.conf` file.
