### ISSUE TITLE
cmusfm init does not do anything apparent

### ISSUE THREAD

**Issue by delexi** [Arkq/cmusfm#7]
Hello!

I installed cmusfm vor the AUR (ArchLinux User Repository) and ran `cmusfm init`. The call did not return and did not issue any output. I expected it to open a browser window to let me grant access to it from my lastfm account.

I then went to the last.fm page and could not find said setting. Admittedly, last time I did this, the side was still on the old version.

I am a bit lost here, what are my next steps?

EDIT: Just after I posted this, the command returned with the following error message:
```
$ cmusfm init
Error: scrobbler authentication failed
Error: unable to write file: /home/delexi/.config/cmus/cmusfm.conf
```
Maybe this is a problem with last.fm?

**Comment by Arkq** [comment]
Hi!

It seems, that there is some issue with the last.fm itself. The root of the issue you've described is network-based - it seems... I've just run `cmusfm init` by myself and it's hanged too. I will check this out more thoroughly tomorrow.

If there is some issue with the last.fm scrobbling API, it is nothing I can help about. However, the initialization should not hang "forever", that's for sure :D So, I will try to improve error handling.

But like I've said, it has to wait until tomorrow. Sorry for the inconvenience :/

**Comment by delexi** [comment]
No problem, take your time. Thanks for the quick reaction!

**Comment by delexi** [comment]
I just retried this and now got the expected (I think) output:
```
$ cmusfm init
Open this URL in your favorite web browser and afterwards press ENTER:
  http://www.last.fm/api/auth/?api_key=67082e45dab1f6433da72a00e3bc037a&token=fcc63475bacb3a3b1941aa8d48a09141
```
I did as I was told, opened said URL in my browser and granted cmusfm access. After that I returned to my console window and pressed enter. I was presented with the same error message as yesterday:
```
Error: scrobbler authentication failed
Error: unable to write file: /home/delexi/.config/cmus/cmusfm.conf
```

**Comment by Arkq** [comment]
It is rather strange, that you've got authentication failure still. Today the Last.fm service is working as expected, so there is no lag - however, like I previously said, I have to fix this too, in order to prevent similar issues in the future.

The second error is rather simple (I've already fixed this, but it's not in the master yet). It seems, that you are using cmus < 2.6.0, and the directory structure which cmusfm expects is not created (~/.config/cmus/).

Right now, I'm trying to refactor code a little bit in order to provide better error messages. Give me an hour or so. After that, I will check what might be causing this "authentication failure" :).

**Comment by delexi** [comment]
The authentication error is now gone -- I am not sure why. Maybe the API just needed some time for the authentication to be peristed, or something along those lines.

Then, I manually created ~/.config/cmus/ which fixes my second problem!

... and now cmusfm is scrobbling -- nice work! :)

**Comment by Arkq** [comment]
OK.
I'm glad, that everything is working as expected now.
